### ISSUE TITLE
geosearch aroundLatLng error

### ISSUE THREAD

**Issue by mhdHussein** [arpit2438735/nativescript-algolia#10]
hi there ,
I am writing an ios version of my android app using nativescript-angular

everytime I search aroundLatLng I get the error

Error : {"status":400,"reason":"Invalid value for \"aroundLatLng\" parameter, expected float"}

how do I resolve this

```
this.index.search(this.searchTerms , {
              aroundLatLng : "37.788211,-122.41199759999999",
              aroundRadius: this.radius

          }  , (content , err) => {

              if(err){
                  console.log("Error : " + JSON.stringify(err));
              }else{
                  console.log("RESULT IS : " + JSON.stringify(content));
              }

          });
```

**Comment by arpit2438735** [comment]
The reason is already messaged in the response.
You are sending as string.It should be float

`aroundLatLng : 37.788211,-122.41199759999999`

**Comment by mhdHussein** [comment]
Hi @arpit2438735 
```

this.index.search(this.searchTerms , {
              aroundLatLng : 37.788211,-122.41199759999999,
              aroundRadius: this.radius

          }  , (content , err) => {

              if(err){
                  console.log("Error : " + JSON.stringify(err));
              }else{
                  console.log("RESULT IS : " + JSON.stringify(content));
              }

          });
```
in the documentation it is a string and if I do as you said , it will not be a valid Object
it tried string I tried trimming the decimal points , I tried parseFloat
and I also tried 
aroundLatLng : [37.788211,-122.41199759999999]

nothing seems to be working , I get the same error every time

**Comment by arpit2438735** [comment]
@mhdHussein https://github.com/algolia/algoliasearch-helper-js/issues/516 <- This might help you

**Comment by mhdHussein** [comment]
@arpit2438735 

I tried to use this helper library but it does not work well with the native script algolia library , it works with the javascript one (it worked before on my ionic version of the app)
and when I install the javascript algoila library the app crashes ,
this is the only plugin that does not crash the app but I get this frustrating error
I also tried the suggestions In that post among many many others , nothing works

please help

**Comment by arpit2438735** [comment]
I will have a look into it.Can you give me sample example for it? Like in your what is `this.radius`

**Comment by mhdHussein** [comment]
ok @arpit2438735 

in the constructor I initialize the client and the index like so

```
this.client = new Algolia('###', '#############');

      this.index = this.client.initIndex('myindex');
```

then I get the radius (which is a number e.g 1000) from the local storage , 
as it was stored in the previous page

and I also get the latitude and longitude from the route queryParams and convert them to floats like so

```
this.radius = Number(localStorage.getItem('radius')) * 1000 || 1000;

          let latLng:string = parseFloat(this.lat).toFixed(4) + ',' + parseFloat(this.lng).toFixed(4);
```

then i do the query like so
```

   this.index.search(this.searchTerms , {
              aroundLatLng : latLng,
              aroundRadius: this.radius

          }  , (content , err) => {

              if(err){
                  console.log("Error : " + JSON.stringify(err));
              }else{
                  console.log("RESULT IS : " + JSON.stringify(content));
              }

          });
```

where this.searchTerms is a string that I got from the previous page using the route queryParams
and I made sure that I got the data from the route params correctly using console logs

**Comment by prestopasto** [comment]
I can confirm this bug as I am seeing the exact same thing.  I am building the same query on Android and all is working as expected.

I tried hardcoding a location like the user did here with no better outcome: [/algolia/algoliasearch-helper-js/issues/516](https://github.com/algolia/algoliasearch-helper-js/issues/516)
```
options.aroundLatLng = "55.828972, -4.2242689";
```

It does appear there is a conversion issue happening somewhere.
Here is the request body from an iOS search pulled from the Algolia admin area:

```
{
  "params": "analytics=false&aroundLatLng=6.36598832743064e-314,4.6600127854048e-33&aroundLatLngViaIP=false&aroundRadius=500&getRankingInfo=true&hitsPerPage=10&page=0&query="
}
```

And here is the response from the same request coming from Android:

```
{
  "params": "analytics=false&aroundLatLng=55.828972%2C%20-4.2242689&aroundLatLngViaIP=false&aroundRadius=all&attributesToRetrieve=*&facets=%5B%5D&getRankingInfo=true&hitsPerPage=10&page=0&query=&restrictSearchableAttributes="
}
```


As you can see, the aroundLatLng parameter seems to get mangled somewhere.

On a related note, ```aroundRadius = "all"``` crashes iOS but is working on Android.

Please let me know if there is anything else I can help to troubleshoot.

**Comment by arpit2438735** [comment]
I see...I didn't get a time to follow up the issue...will look into it now.

**Comment by arpit2438735** [comment]
@prestopasto got the issue in iOS.I will try to fix it.

Meanwhile I want to ask one more thing does it failing for `Android` as well?

**Comment by prestopasto** [comment]
No, it passes the correct geo coordinates on Android and returns the correct results.  Even with all the same options and a hardcoded location string.

**Comment by arpit2438735** [comment]
Hi @mhdHussein @prestopasto Can you guys test now for `aroundLatLng`?
Next, is to fix for `aroundRadius = "all"`

**Comment by prestopasto** [comment]
@arpit2438735 That seems to work!  I'm getting good requests in from the phones geo-location searches now.

Can I make 1 request?  I added a **null** check to your key check with ``` && args[key] ```:

```
    if (key === "aroundLatLng" && args[key]) {
        const latlng = args[key].replace(/ /g, "").split(",");
        queryObject[key] = LatLng.alloc().initWithLatLng(latlng[0], latlng[1]);
    } else {
        queryObject[key] = args[key];
    }
```


I have been setting my options like this:

```
// initialize options
    let options = {
      hitsPerPage: 10,
      page: 0,
      restrictSearchableAttributes: "",
      analytics: false,
      attributesToRetrieve: "*",
      aroundLatLngViaIP: false,
      aroundLatLng: null,
      aroundRadius: null,
      facets: "[]",
      getRankingInfo: true
    };

// add location data if it exists
    if (this.location.lat && this.location.lng) {
      options.aroundLatLng = `${this.location.lat}, ${this.location.lng}`;
      options.aroundRadius = "all";
    }
```
So I need to check for **null** on that property otherwise an error is throw when trying to ```.replace(...```

I'd probably ask for the same check on whatever fix has the ```aroundRadius``` too if it's not too much trouble.

**Comment by arpit2438735** [comment]
@prestopasto Does `null` is a valid param in algolia if you do it from other algolia library?

I am currently fixing aroundRadius as well.Don't worry about that and no one is troubling anyone 😄  .It's good to find bug, in that way I will make my library better and bug free.

**Comment by prestopasto** [comment]
https://www.algolia.com/doc/api-reference/api-parameters/aroundLatLng/?language=swift

This says that the type is ```string``` and that ```null``` is the "engine default" value for ```aroundLatLng```.  It doesn't explicitly say that null is a valid param.

Either way you want to handle it is fine with me.  I can change my implementation if needed.

**Comment by arpit2438735** [comment]
For now, you can do that.I will dig more and if needed I will do at my end as well.

**Comment by arpit2438735** [comment]
@prestopasto Can you try latest master? 
I added a fix for `aroundRadius` as well.If that works for you.I will publish new release then

**Comment by prestopasto** [comment]
Thanks @arpit2438735.  I didn't get a chance to try it this morning.  I will try either tonight or tomorrow morning.

**Comment by prestopasto** [comment]
@arpit2438735 

Ok, So I can't figure out how to build the latest version after downloading it.  I can download a *.tgz file from the latest commit.   I thought running the pack.sh script was enough, but that doesn't generate the .js files.  And after that I should be able to tns plugin add <folder>, I think.  But I'm not doing the middle part right.  Any tips?

**Comment by arpit2438735** [comment]
That's correct.Create tgz file and unzip it and replace your current plugin code in node_modules with this new code.After that delete ios folder in platform and try to start again `tns run ios`

**Comment by prestopasto** [comment]
@arpit2438735 Sorry, I know I must be doing something wrong.  But I run pack.sh on the downloaded git repo src.  Extract the generated tgz file.  Add it to my project with ```tns plugin add <path-to-folder>```.  That seems to work fine.  It builds ok but there is an error when it tries to launch.  I think it is something to do with Webpack, but the issue wasn't there before.

**Comment by arpit2438735** [comment]
@prestopasto What error you are getting? I am thinking to release it to npm repo.What say?
You can test it from there.As per my testing it's working fine.

**Comment by prestopasto** [comment]
Specifically: ```webpackMissingModule unexpected token '!'``` . Webpack is doing some weird wrapping of this line ```this.client = new Algolia("***", "***");``  because it is a ```new``` constructor and takes parameters.  But it wasn't doing it before.  Unless you changed how something is exported in your library, I very likely messed something up when packaging the plugin on my end.

I would say you are probably good to release it to npm.

**Comment by arpit2438735** [comment]
Try to delete node module and reinstall.
Release the new version.You can try now

**Comment by prestopasto** [comment]
@arpit2438735 I've updated to 1.1.0.  Build and execution is fine.  Search results don't seem to be there.

When setting ```aroundRadius: all``` on iOS the term param passed to Algolia is ```aroundRadius=1```

Here is the body of a search result passed from an iOS client to Algolia
```
"params": "analytics=false&aroundLatLng=32.4421,-96.8293&aroundLatLngViaIP=false&aroundRadius=1&getRankingInfo=true&hitsPerPage=10&page=0&query="
```
I'm not sure, but I think it may actually need to be the string "all".(?)

https://www.algolia.com/doc/api-reference/api-parameters/aroundLatLng/?language=swift

**Comment by arpit2438735** [comment]
I set `aroundRadius` is `1` for **all**.I did as per swift code internally doing the same thing.
Can you let me know if I send all params from Android then what it send in as params?

**Comment by prestopasto** [comment]
The same query coming from Android looks like this:

```
"params": "analytics=false&aroundLatLng=32.4420%2C%20-96.8293&aroundLatLngViaIP=false&aroundRadius=all&attributesToRetrieve=*&facets=%5B%5D&getRankingInfo=true&hitsPerPage=10&page=0&query=&restrictSearchableAttributes="
```

It looks like it sends 'all' as a string:  ```aroundRadius=all```

**Comment by arpit2438735** [comment]
I see.I will try to do the same thing.

**Comment by arpit2438735** [comment]
@prestopasto I added a fix in the latest release.Have a look and let me know if it works for you?

**Comment by prestopasto** [comment]
That looks like it fixed it!

**Comment by prestopasto** [comment]
Thanks @arpit2438735!

**Comment by arpit2438735** [comment]
Your welcome 👍
