### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by prestopasto** [arpit2438735/nativescript-algolia#11]
Hello,

I am using this plugin with NativeScript-Angular 6.1 and was having build issues on iOS.  The build error was "overlapping accesses to self" with the AlgoliaSearch-Client-Swift pod.

After updating the Podfile for this plugin to the following it started working fine:

`platform :ios, '8.0'

pod 'AlgoliaSearch-Client-Swift', '~> 5.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end`

I changed it to use version 5.0+ of the AlgoliaSearch Client and changed the Swift version to 4.0.

**Comment by arpit2438735** [comment]
I will have a look.Thanks for pointing it out.

**Comment by arpit2438735** [comment]
Hi @prestopasto I didn't face any issue related to updated `AlgoliaSearch-Client-Swift` version with `Swift`.I will push the latest code to master as well and release, you can have a look

**Comment by arpit2438735** [comment]
@prestopasto take update release and try it again.If any issue arise do let me know 👍

**Comment by prestopasto** [comment]
Awesome!  Thanks @arpit2438735.  I will check it out tonight and see if that fixes it.

**Comment by prestopasto** [comment]
@arpit2438735 After updating to 1.0 I get an error that the module is not found.  It appears there is no index file in the package after installing via npm.

![screen shot 2018-08-31 at 4 15 08 pm](https://user-images.githubusercontent.com/6289780/44936118-10b77600-ad39-11e8-8d30-2a9d59ce5fbc.png)

**Comment by arpit2438735** [comment]
@prestopasto Can you try again with latest release?

I added back all the `ts` file in order to support for typescript language

**Comment by prestopasto** [comment]
Hey @arpit2438735, that seems to have fixed this issue.  Everything I am using on Android seems to still be in working.  iOS builds now and mostly works.  I believe the issue I am running into is #10. I think this issue can be closed and we can pick up the discussion over there.

Thank you so much for taking the time to look into this.
