### ISSUE TITLE
Support for realtime full-text search / faceting 

### ISSUE THREAD

**Issue by b02505048** [arpit2438735/nativescript-algolia#15]
This is really a **great plugin**!

By the way, will it support for the super duper powerful feature of Algolia (realtime full-text faceting)??

Now it seems like still have to press a button to trigger the `index.search`, am I right? Thank you!

**Comment by arpit2438735** [comment]
Thanks a lot!!!

You can do on your side, rather than clicking on button you can have same search on each key stroke

**Comment by b02505048** [comment]
Yeah I did it with `textChange`, now it works like charm
