### ISSUE TITLE
Blackout on iOS without showing error

### ISSUE THREAD

**Issue by b02505048** [arpit2438735/nativescript-algolia#16]
**tns:** v4.2.0
**tns-ios:** 4.2.0
**tested iOS:** 10.3 & 12.1 (device & simulator)
**nativescript-algolia**: ^1.2.0
**XCode**: 10.1
**Swift**: 3.0 & 4.0 (both tried)

It blackout when calling `index.search` on iOS
**UPDATED:**  blackout once called `algoliaClient.initIndex('contacts')` on iOS

Any idea?

**Comment by arpit2438735** [comment]
How you are calling? Can you paste your snippet over here

**Comment by b02505048** [comment]
Hi @arpit2438735, 
Here is the [Blackout Screen Record](https://imgur.com/MVW4NyL) 

```
<template>
<Page>
    <GridLayout rows="60, *">
        <TextField row="0" v-model='keyword' hint="Try smth..." @textChange="search" />

        <ScrollView row="1" orientation="vertical">
                <StackLayout v-show="searchResults.length != 0">
                        <StackLayout v-for="result in searchResults" :key="result.id" orientation="vertical">
                                <Label :text="result.name />
                        </StackLayout>
               </StackLayout>
        </ScrollView>
    </GridLayout>
</Page>
</template>

<script>
import { Algolia } from "nativescript-algolia";
const algoliaClient = new Algolia('APP_ID', 'API_KEY');
...
search() {
  let index = algoliaClient.initIndex('contacts');
  index.search(this.keyword, (success, error) => {
    this.searchResults = success.hits
    if(success.hits.length == 0) console.log('No result found...')
  })
}
...
</script>
```

it works very well on Android and only will blackout on iOS
I tried to change the Swift from 4.0 to 3.0, but still no luck, any idea? Thanks!

**Comment by arpit2438735** [comment]
Hmm, interesting can you change from `textChange` and use submit button in iOS and then check if it works?

**Comment by b02505048** [comment]
@arpit2438735, I tried but still no luck...

**Comment by arpit2438735** [comment]
Ok...I tested in my iOS and it's working

**Comment by b02505048** [comment]
@arpit2438735  Well...may you share the versions of the development environment in your case? Thank you!

**Comment by arpit2438735** [comment]
I am using Xcode 9, Swift 4 and iOS 11 for testing

**Comment by b02505048** [comment]
My Xcode is 10.1 (latest), can't figure out if it's a problem...

**Comment by b02505048** [comment]
I find out it happened when called `initIndex`
Once called `algoliaClient.initIndex('INDEX')`, iOS blackout and freeze for a moment...

```
// node_modules/nativescript-algolia/algolia-index.ios.js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var utils_1 = require("./utils");
var index;
var AlgoliaIndex = (function () {
    function AlgoliaIndex(client, name) {

        console.log('Algolia initing...')                            // Printed
        client.indexWithName("").isMemberOfClass(Index);

        console.log('Algolia determining isMemberOfClass(Index)')    // Not printed

        index = client.indexWithName(name);
        console.log('Algolia initiated!')                            // Not printed

    }
    AlgoliaIndex.prototype.search = function (query, args, handler) {
        var queryObject = Query.alloc().initWithQuery(query);
        if (typeof args === "function") {
            handler = args;
        }
  ...
```

Run the code below right after `function AlgoliaIndex(client, name) { ...`
``` 
console.log('Client:', client)    // return 'Client: {}'
console.log('Name:', name)    // return 'Name: "contacts"'
```

I guess the problem comes out from here, any idea? @arpit2438735 
Is it related to the update of [algolia](https://github.com/algolia/algoliasearch-client-javascript/pull/695) ?

**Comment by b02505048** [comment]
Finally fixed with moving `algoliaClient` into `search()`

```
search() {
  const algoliaClient = new Algolia('APP_ID', 'API_KEY')
  const index = algoliaClient.initIndex('contacts')
  ...
}
```

And everything works magically NOW. Thank you for helping @arpit2438735 Cheers!

**Comment by arpit2438735** [comment]
Awesome...nice to hear that
