### ISSUE TITLE
Won't compile on iOS with NativeScript 5.2 (SWIFT_VERSION)

### ISSUE THREAD

**Issue by keerl** [arpit2438735/nativescript-algolia#19]
I just tried installing this plugin on the newest version of NativeScript but the build it failing on iOS. This is the error I am getting:
```
[!] Unable to determine Swift version for the following pods:

- `AlgoliaSearch-Client-Swift` does not specify a Swift version and none of the targets (`coop`) 
integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the 
`SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by arpit2438735** [comment]
@keerl I will have a look into this one.What exact error you getting? This stack-trace looks like it's a warning

**Comment by keerl** [comment]
[Here](https://i.imgur.com/t5DiCSe.png) is a screenshot of the error. Thanks for looking into this!

**Comment by arpit2438735** [comment]
@keerl Can you try this one https://stackoverflow.com/a/54584360/1306308? 

I specifically removed it, as one of developer was also using algolia and some other plugin and every plugin has different swift version cause of which it create a problem.Ideally we should bound developer to use specific version if supported for all latest one.

**Comment by keerl** [comment]
Yes, this works! Thank you for the quick fix!

**Comment by keerl** [comment]
This seems like a better way to fix the issue long term. https://stackoverflow.com/a/55218757/5530933
