### ISSUE TITLE
NativeScript iOS Build Fails With AlgoliaSearch-Client-Swift

### ISSUE THREAD

**Issue by falodunos** [arpit2438735/nativescript-algolia#20]
[!] Unable to determine Swift version for the following pods:

- `AlgoliaSearch-Client-Swift` does not specify a Swift version and none of the targets (`loopmi`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by arpit2438735** [comment]
It's a similar issue https://github.com/arpit2438735/nativescript-algolia/issues/19#issuecomment-472847392.

Lot of `developer` facing same issue.Let me dig and found generic fix.Meanwhile you can have above solution.

**Comment by arpit2438735** [comment]
@falodunos You are facing the issue again or stuck somewhere? or can we close this issue?

**Comment by arpit2438735** [comment]
Closing this issue as no new comment and concern from longer time.Feel free to reopen if you have any concern.
