### ISSUE TITLE
adding a geo search

### ISSUE THREAD

**Issue by mchallenger88** [arpit2438735/nativescript-algolia#23]
I want to do a geo search so in testing I did the following which should return 3 results. None are returned. I think the syntax is probably incorrect:

 index.search(criteria, [{aroundLatLng: '41.88271, -87.62495'}, {aroundRadius: 150000}], content => {
            console.log(content)
        });

Can you tell me the correct syntax for adding these parameters?

**Comment by arpit2438735** [comment]
@mchallenger88 Can you try like this -> ```
index.search(criteria, {aroundLatLng: '41.88271, -87.62495', aroundRadius: 150000}, content => {
console.log(content)
});``` or remove one parameter like `aroundRadius` or `aroundLatLng` as per the docs I can see that they are expecting as an object and I see example which has only one param.

**Comment by mchallenger88** [comment]
@arpit2438735 - Thanks. Using just one parameter worked. Two parameters separated by a comma did not work. Thanks for your help!

**Comment by arpit2438735** [comment]
Awesome.I will close this bug
