### ISSUE TITLE
Error using hits per page

### ISSUE THREAD

**Issue by anuragd7** [arpit2438735/nativescript-algolia#5]
We tried to use the hitsPerPage parameter while querying the algolia index but we are getting an error as follows:

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method requestCompleted failed

TypeError: handler is not a function
File: "file:///data/data/org.nativescript.qbank/files/app/tns_modules/nativescript-algolia/algolia-index.js, line: 41, column: 15

StackTrace: 
Frame: function:'requestCompleted', file:'file:///data/data/org.nativescript.qbank/files/app/tns_modules/nativescript-algolia/algolia-index.js', line: 41, column: 16

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
at com.tns.Runtime.callJSMethod(Runtime.java:912)
at com.tns.Runtime.callJSMethod(Runtime.java:896)
at com.tns.Runtime.callJSMethod(Runtime.java:888)
at com.tns.gen.com.algolia.search.saas.CompletionHandler.requestCompleted(CompletionHandler.java:12)
at com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.onPostExecute(AbstractClient.java:702)
at com.algolia.
Our code const queries = [{
indexName: 'Questions',
query: value,
params: {
hitsPerPage: 3,
page: 0,
},
}];

this.client.search(queries, (success, error) => {
console.log("Result returned from algolia ");
});
Not sure if you got the message on upwork? please confirm

**Comment by arpit2438735** [comment]
Hey @anuragd7 you are facing issue in which platform and version of OS? It works fine in iOS

**Comment by anuragd7** [comment]
Got this while trying the plugin for android. Tns 3.1.2. Have not tried it on ios yet. Let me know if you need more info

**Comment by arpit2438735** [comment]
Ok I will have a look for android 👍

**Comment by arpit2438735** [comment]
Hey @anuragd7 I found the problem.If you are stuck meanwhile there's a workaround for it
```
        index = algolia.initIndex('getstarted_actors');

         index.search('nicolas', (success, error) => {
            if(error) {
                console.log(JSON.stringify(error));
                return;
            }

            this.message = success.hits;
            console.log(JSON.stringify(success)); // uncomment this code or add this code as below result is coming in this log
         });

        /* Example of multiple quries */
        var queries = [{
           indexName: 'getstarted_actors',
           query: 'nicolas',
           params: {
               hitsPerPage: 3
           }
        }, {
           indexName: 'getstarted_actors',
           query: 'kate',
           params: {
               hitsPerPage: 3
           }
        }];

        algolia.search(queries, (success, error) => {
           console.log(JSON.stringify(success)); // This console is not working
        });
```

**Comment by arpit2438735** [comment]
Hi @anuragd7 I fixed the issue, you can take latest change from git or download latest package from npm which is `0.0.2`

**Comment by anuragd7** [comment]
Thanks Arpit will try it out.

**Comment by anuragd7** [comment]
Hi Arpit
Still seem to be having problems using the plugin. 
Here is my code: 
`this.client = new Algolia('xxxxxxxxxxxx', 'xxxxxxxxxxxx');
`
` const queries = [{
        indexName: 'Questions',
        query: value,
        params: {
          page: 2,
          hitsPerPage: 30,
        },
      }];`

`  
    this.client.search(queries, (success, error) => {
          console.log("Result returned from algolia: " + JSON.stringify(success.results));
      });
    }
`
it is returning the same result even if I change the page parameter to 3/4 or anything. 

in the return payload it is saying, page: 0 always, even if I changed the page no.:

matchLevel":"none","matchedWords":[]},{"value":"null","matchLevel":"none","matchedWords":[]}]}}],"nbHits":7413,"page":0,"nbPages":34,"hitsPerPage":30,"processingTimeMS":3,"exhaustiveNbHits":false,"query":"a","params":"query=a","index":"Questions"}]

**Comment by arpit2438735** [comment]
Hi @anuragd7 I didn't get the problem what you are facing.What is the expected outcome if you change the params?

**Comment by anuragd7** [comment]
We want to implement incremental search  as the user scrolls through the results. Algolia supports incremental search by updating "page" parameter while calling the api. For reference please refer to [this.](https://www.algolia.com/doc/api-reference/api-parameters/page/)

The plugin it is not working with the "page" parameter as expected. The page parameter continues to return 0 no matter what page parameter we pass in the request. That is why I reported the issue.

**Comment by arpit2438735** [comment]
@anuragd7 I fixed the issue, take the latest changes #6

**Comment by arpit2438735** [comment]
@anuragd7 Are you still facing the same issue?

**Comment by anuragd7** [comment]
Thanks Arpit. The issue is fixed on android
