### ISSUE TITLE
IOS: multipage search - page parameter not changing on successive searches

### ISSUE THREAD

**Issue by anuragd7** [arpit2438735/nativescript-algolia#7]
Hi Arpit
On IOS  when we are passing the page parameter  like so 

```
const queries = [{
                indexName: 'trial',
                query: searchPhrase,
                params: {
                    page: pageToSearchDetail.pageNo,
                    hitsPerPage: 20,
                },
            }];

```
Then the page parameter does not seem to be passing correstly in IOS only (in android it works fine) In IOS we are always getting the results for page 0.

Please take a look.
Thanks

**Comment by arpit2438735** [comment]
@anuragd7 Fixed the issue, take the latest version 0.0.4
