### ISSUE TITLE
Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by RaphaelJenni** [arpit2438735/nativescript-algolia#8]
Got that error message on initialization:
```
System.err: TypeError: Cannot read property 'extend' of undefined
System.err: File: "file:///data/data/com.app.APP/files/app/tns_modules/nativescript-algolia/algolia-index.js, line: 35, column: 65
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///data/data/com.app.APP/files/app/tns_modules/nativescript-algolia/algolia-index.js', line: 35, column: 66
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.app.APP/files/app/tns_modules/nativescript-algolia/index.js', line: 3, column: 23
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.app.APP/files/app/shared/services/stations.service.js', line: 5, column: 30
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.app.APP/files/app/shared/services/radio-player.service.js', line: 9, column: 26
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.app.APP/files/app/shared/components/radio-access-bar/radio-access-bar.component.js', line: 5, column: 30
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/com.app.APP/files/app/shared/components/component.module.js', line: 12, column: 36
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
```

**Comment by arpit2438735** [comment]
Hi @RaphaelJenni Can you share your code just to see how you are initialising?

**Comment by RaphaelJenni** [comment]
I'm using nativescript with angular. The initialization looks like that:

```
import { Algolia } from 'nativescript-algolia'

private client: Algolia;

private initAlgolia(): void {
    this.userService
      .getHttpHeaders$()
      .switchMap((headers: HttpHeaders) => this.http.get(`${Config.api.baseUrl}/searchKey`, { headers }))
      .subscribe((response: any) => {
        const searchKey: string = response['key'];
        console.log(`Search Key received: ${searchKey}`);
        this.client = new Algolia(Config.algoliaConfig.appId, searchKey);
      });
  }
```

**Comment by arpit2438735** [comment]
Hi @RaphaelJenni `this.client = new Algolia(Config.algoliaConfig.appId, searchKey);` // in place of `searchKey` it should be `token`, I am not sure.More details how to use here's the example https://github.com/arpit2438735/nativescript-algolia/blob/master/demo/app/main-view-model.ts#L12

**Comment by RaphaelJenni** [comment]
Same error if I use the `token` directly.

Side notice, the api isn't the same as the javascript api anymore.

**Comment by arpit2438735** [comment]
Regard to javascript api I haven't seen the new update for Algolia Javascript API.I will change accordingly to what they have latest

**Comment by arpit2438735** [comment]
> Same error if I use the token directly.

Can I see your new code if possible?

**Comment by RaphaelJenni** [comment]
Same as above but with the token instead of the searchkey.

**Comment by arpit2438735** [comment]
How you are running the app? Looks like it didn't install `algoliasearch-android` version for nativescript

**Comment by RaphaelJenni** [comment]
What do you mean with "How are you running the app". I run it via tns run android.

**Comment by arpit2438735** [comment]
Hi @RaphaelJenni I just ran in my local android the demo and it worked for me.Can you try this repo demo page in your android?

**Comment by RaphaelJenni** [comment]
The build gets stuck in the prepare phase. Probably too old NS version. But have you tried the plugin with an angular app?

**Comment by arpit2438735** [comment]
Yes, one of angular version example is https://github.com/jlooper/quicknoms-app/blob/eab96da7692a7b67cc3b5165a29677738be8aac8/app/recipe-search/recipe-search.component.ts

**Comment by RaphaelJenni** [comment]
Hmm... interesting

**Comment by RaphaelJenni** [comment]
Somehow the error vanished... I'll keep you posted.

**Comment by arpit2438735** [comment]
@RaphaelJenni is this plugin is working for you ? and if yes shall I close this issue?

**Comment by RaphaelJenni** [comment]
Yes, it works, might was some stupid nativescript error. Thanks for your help.
